#ifndef OQS_UTIL_H
#define OQS_UTIL_H

///// OQS_TEMPLATE_FRAGMENT_DEFINE_HYBRID_MACROS_START
#define IS_RSA_HYBRID_ALG_NAME(alg) ( \
				strcmp(alg, "ssh-rsa3072-oqsdefault") == 0)

#define IS_RSA_HYBRID(alg) ( \
				alg == KEY_RSA3072_OQSDEFAULT)

#define IS_ECDSA_HYBRID(alg) ( \
				alg == KEY_P256_OQSDEFAULT || \
				alg == KEY_P521_RAINBOW_VC_CLASSIC || \
				alg == KEY_P521_RAINBOW_VC_CYCLIC || \
				alg == KEY_P521_RAINBOW_VC_CYCLIC_COMPRESSED)
///// OQS_TEMPLATE_FRAGMENT_DEFINE_HYBRID_MACROS_END

#define IS_HYBRID(alg) (IS_RSA_HYBRID(alg) || IS_ECDSA_HYBRID(alg))

///// OQS_TEMPLATE_FRAGMENT_ASSIGN_PQ_KT_START
#define IS_OQS_KEY_TYPE(type) ( \
				(type) == KEY_OQSDEFAULT || \
				(type) == KEY_RAINBOW_VC_CLASSIC || \
				(type) == KEY_RAINBOW_VC_CYCLIC || \
				(type) == KEY_RAINBOW_VC_CYCLIC_COMPRESSED || \
				IS_HYBRID(type))
///// OQS_TEMPLATE_FRAGMENT_ASSIGN_PQ_KT_END

///// OQS_TEMPLATE_FRAGMENT_DEFINE_PQ_SWITCH_CASES_START
#define CASE_KEY_OQS \
	case KEY_OQSDEFAULT: \
	case KEY_RAINBOW_VC_CLASSIC: \
	case KEY_RAINBOW_VC_CYCLIC: \
	case KEY_RAINBOW_VC_CYCLIC_COMPRESSED
///// OQS_TEMPLATE_FRAGMENT_DEFINE_PQ_SWITCH_CASES_END

///// OQS_TEMPLATE_FRAGMENT_DEFINE_HYBRID_SWITCH_CASES_START
#define CASE_KEY_RSA_HYBRID \
	case KEY_RSA3072_OQSDEFAULT

#define CASE_KEY_ECDSA_HYBRID \
	case KEY_P256_OQSDEFAULT: \
	case KEY_P521_RAINBOW_VC_CLASSIC: \
	case KEY_P521_RAINBOW_VC_CYCLIC: \
	case KEY_P521_RAINBOW_VC_CYCLIC_COMPRESSED
///// OQS_TEMPLATE_FRAGMENT_DEFINE_HYBRID_SWITCH_CASES_END

#define CASE_KEY_HYBRID \
	CASE_KEY_RSA_HYBRID: \
	CASE_KEY_ECDSA_HYBRID

#endif /* OQS_UTIL_H */
